apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: myapp-deploy
  annotations:                 # kubectl rollout history CHAGE-CAUSE 필드 설정
    kubernetes.io/change-cause: My Golang Web App Version 3
spec:
  strategy:
    type: RollingUpdate        # 배포 전략: 롤링업데이트(ramped)
    rollingUpdate:
      maxUnavailable: 1       # 한번에 하나씩 업데이트 진행
      maxSurge: 1              # 특정 시점에 추가 허용하는 Pod 개수 +1
  minReadySeconds: 20          # 새 파드 생성 시 기존 파드 유지시간 20초
  replicas: 3
  selector:
    matchLabels:
      app: myapp-deploy
  template:
    metadata:
      labels:
        app: myapp-deploy
    spec:
      containers:
        - image: ghcr.io/c1t1d0s7/go-myweb:v3.0
          name: myapp
          ports:
            - containerPort: 8080
          readinessProbe:      # 컨테이너 애플리케이션이 요청을 받을 준비가 되었는지 확인
            periodSeconds: 1   # 프로브 주기(기본 10초 간격)
            httpGet:           # path에 지정된 경로로 http request 요청을 보내 확인
              path: /
              port: 8080
