apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-lim
spec:
  containers:
    - image: ghcr.io/c1t1d0s7/go-myweb:alpine
      name: myapp
      resources:
        limits:
          cpu: 0.5
          memory: 20Mi
