apiVersion: v1
kind: Pod
metadata:
  name: example-pod-env1
spec:
  containers:
  - name: example-pod-env1
    image: ubuntu/apache2:2.4-22.04_edge
    ports:
    - containerPort: 80
      protocol: TCP
    env:
    - name: ECHO1
      value: "Hello World"
    - name: NODE_NAME
      valueFrom:                     # 환경 변수의 값을 가져오는 방법 지정 
        fieldRef:                    # Kubernetes의 필드 값을 참조하는 방법 지정
          fieldPath: spec.nodeName   # 필드의 경로 지정
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP_ADDRESSES
      valueFrom:
        fieldRef:
          fieldPath: status.podIP # Pod가 만들어지고 난 후 상태 필드

# 환경변수는 env 필드에서 정의됩니다. 
# name 필드는 환경변수의 이름을 지정하고, valueFrom 필드는 해당 환경 변수의 값을 가져올 위치를 지정합니다.
# valueFrom 필드 지정 방식 2가지 
# - fieldRef
#   - Kubernetes의 필드 값을 참조하는 방법 
#   - 필드의 경로 지정, 경로는 참조하려는 리소스의 종류에 따라 달라짐
# - resourceFieldRef : 
#
# 실행 중인 리소스의 매니페스트 파일을 참조하는 것이다 
# 이때 실행 중인 매니페스트 파일은 etcd, api-server가 동일하게 가지고 있다.
