apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-cm
spec:
  containers:
    - image: ghcr.io/c1t1d0s7/go-myweb:alpine
      name: myapp
      env:
      - name: MESSAGE
        valueFrom:
          configMapKeyRef:
            name: myapp-message   # ConfigMap 오브젝트 이름
            key: message          # ConfigMap에서 참조하고자 하는 value에 대응하는 key
      args:              
      - $(MESSAGE)                # configMap의 데이터를 받아온 환경변수를 Pod 실행 시 인자값으로 전달
      ports:
      - containerPort: 8080
        protocol: TCP
