apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-arg
spec:
  containers:
  - name: myapp
    image: ghcr.io/c1t1d0s7/go-myweb:alpine
    # 인수를 변경하여 서비스 포트를 변경
    args:
    - -port=8080
    ports:
    - containerPort: 8088
      protocol: TCP
