apiVersion: v1
kind: ReplicationController
metadata:
  name: example-rc
spec:
  replicas: 1
  selector:
    appname: example-app
  template:
    metadata:
      labels:
        appname: example-app
    spec:
      containers:
      - name: example-container
        image: httpd:2.4
        ports:
        - containerPort: 80
          protocol: TCP
