apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simpleweb-datastore-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: simpleweb-datastore-pv
  storageClassName: ''
