apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simpleweb-datastore-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: datastore
  # storageClassName: '' 동적 프로비저닝 사용 x
