apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-namedport
spec:
  type: ClusterIP
  selector:
    app: myapp-rs-namedport
  ports:
    - name: myapp-http
      port: 80
      targetPort: myapp-http
