apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-rs
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: example-rs
  template:
    metadata:
      labels:
        app: example-rs
    spec:
      containers:
      - name: example-app
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
        ports:
        - containerPort: 8080
          protocol: TCP
