apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-nfs-02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-rs-nfs-02
    template:
      metadata:
        labels:
          app: myapp-rs-nfs-02
      spec:
        containers:
        - name: myapp
          image: nginx
          volumeMounts:
          - name: nfs-share
            mountPath: /usr/share/nginx/html
          ports:
          - containerPort: 80
        volumes:
        - name: nfs-share
          persistentVolumeClaim:
            claimNAme: myapp-pvc-nfs
