- name: reg_var_01
  hosts: web_servers
  tasks:
    - name: Run a shell command and register its output as a variable
      shell: /usr/bin/foo
      register: foo_result
      ignore_errors: true

    - name: Run a Shell command using output of the previous task
      shell: /usr/bin/bar
      when: foo_result.rc == 5
